# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

# DISABLE PIPELINE until repo is public
# chef-oss Buildkite org does not have access to private repos
# pipelines:
#  - verify:
#     description: Pull Request validation tests
#     public: true

slack:
  notify_channel: inspec-notify

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true
  # The tag format to use (e.g. v1.0.0)
  version_tag_format: "v{{version}}"
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"
 
changelog:
  categories:
    - "Type: Enhancement": "Enhancements"
    - "Type: Bug": "Bug Fixes"

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
  - bash:.expeditor/update_version.sh:
      only_if: built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Skip Changelog"
        - "Expeditor: Skip All"

